const TYPES = {
    FETCH_LINKS: 'FETCH_LINKS',
    FETCH_LINKS_FAILURE: 'FETCH_LINKS_FAILURE',
    FETCH_LINKS_SUCCESS: 'FETCH_LINKS_SUCCESS',
    ADD_LINK: 'ADD_LINK',
    ADD_LINK_SUCCESS: 'ADD_LINK_SUCCESS',
    ADD_LINK_FAILURE: 'ADD_LINK_FAILURE',
};

export default TYPES
