const TYPES = {
    FETCH_LINKS: 'FETCH_LINKS',
    FETCH_LINKS_FAILURE: 'FETCH_LINKS_FAILURE',
    FETCH_LINKS_SUCCESS: 'FETCH_LINKS_SUCCESS',
    ADD_LINK: 'ADD_LINK',
    ADD_LINK_SUCCESS: 'ADD_LINK_SUCCESS',
    ADD_LINK_FAILURE: 'ADD_LINK_FAILURE',
    GIVE_VOTE: 'GIVE_VOTE',
    ORDER_BY_VOTE: 'ORDER_BY_VOTE',
    REMOVE_LINK: 'REMOVE_LINK'
};

export default TYPES
